#!/usr/bin/env python3
"""Generate release metadata for a ProotX support bundle release (v1.2.0 schema).

Produces, deterministically:
  - SHA256SUMS                       (sorted; over the four ZIPs + routing + provenance + sbom)
  - provenance/releases/<v>.json     (release manifest)
  - <v>-provenance.json              (flat copy of the release manifest)
  - <v>.spdx.json                    (SPDX 2.3 JSON component inventory)

Per-file inventory is read from each archive's embedded `manifest.json`, which
was generated by scripts/assemble_support.py from the actual archive contents.
"""
import argparse, hashlib, json, os, sys, time, zipfile

ARCHIVES = ["arm64-v8a-assets.zip", "armeabi-v7a-assets.zip", "x86-assets.zip", "x86_64-assets.zip"]

COMPONENTS = [
    {"name": "proot", "version": "5.1.107.92", "license": "GPL-2.0",
     "source": "https://github.com/termux/proot", "scope": "modern source-built"},
    {"name": "talloc", "version": "2.4.3", "license": "GPL-3.0",
     "source": "https://www.samba.org/ftp/talloc/talloc-2.4.3.tar.gz", "scope": "modern source-built"},
    {"name": "libandroid-shmem", "version": "0.7", "license": "BSD-3-Clause",
     "source": "https://github.com/termux/libandroid-shmem", "scope": "modern source-built"},
    {"name": "libandroid-selinux", "version": "14.0.0.11-1", "license": "Apache-2.0",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "busybox", "version": "1.38.0", "license": "GPL-2.0",
     "source": "https://busybox.net/downloads/busybox-1.38.0.tar.bz2", "scope": "modern source-built"},
    {"name": "dropbear/dbclient", "version": "2026.94", "license": "MIT",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "openssl/libcrypto", "version": "3.6.3", "license": "Apache-2.0",
     "source": "https://github.com/openssl/openssl", "scope": "modern source-built"},
    {"name": "termux-auth", "version": "1.5.0-1", "license": "GPL-3.0",
     "source": "https://github.com/termux/termux-auth", "scope": "modern source-built"},
    {"name": "leveldb", "version": "1.23-4", "license": "BSD-3-Clause",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "snappy", "version": "1.3.0", "license": "BSD-3-Clause",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "zlib", "version": "1.3.2", "license": "Zlib",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "pcre2", "version": "10.47", "license": "BSD-3-Clause",
     "source": "https://github.com/termux/termux-packages", "scope": "modern source-built"},
    {"name": "libc++", "version": "r29", "license": "Apache-2.0 WITH LLVM-exception",
     "source": "Android NDK r29 29.0.14206865", "scope": "modern source-built"},
    {"name": "proot_meta", "version": "2a7f6d9", "license": "GPL-2.0",
     "source": "https://github.com/CypherpunkArmory/proot @ 2a7f6d9d46552ed75cf1f2cab2391816f004877b (-DUSERLAND)",
     "scope": "modern source-built, recovered 2019 lineage; legacy frozen counterpart retained"},
    {"name": "proot_meta_leveldb", "version": "998dd31", "license": "GPL-2.0",
     "source": "https://github.com/CypherpunkArmory/proot @ 998dd31b6283e07233ec9004d585bce5ab1a4c27 (-DUSERLAND)",
     "scope": "modern source-built, recovered 2019 lineage; legacy frozen counterpart retained"},
    {"name": "legacy-runtime", "version": "v1.1.0-frozen", "license": "NOASSERTION",
     "source": "https://github.com/Lord1Egypt/ProotX-Assets-Support/releases/tag/v1.1.0",
     "scope": "legacy API 21-28 frozen payload (not source-reproducible)"},
]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dist", required=True)
    ap.add_argument("--version", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--source-commit", required=True)
    ap.add_argument("--repo-root", default=".")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    lock = json.load(open(os.path.join(a.repo_root, "provenance", "sources.lock.json")))

    archives = {}
    all_entries = {}
    modern_64_fail = []
    legacy_debt = []
    for zname in ARCHIVES:
        zpath = os.path.join(a.dist, zname)
        if not os.path.isfile(zpath):
            sys.exit(f"missing archive: {zpath}")
        with zipfile.ZipFile(zpath) as z:
            manifest = json.loads(z.read("manifest.json"))
        entries = manifest["files"]
        all_entries[zname] = entries
        archives[zname] = {
            "size": os.path.getsize(zpath),
            "sha256": sha256(zpath),
            "files": len(entries),
            "common": len(manifest["commonFiles"]),
            "legacy": len(manifest["legacyFiles"]),
            "modern": len(manifest["modernFiles"]),
        }
        for e in entries:
            if e["lane"] == "modern" and e.get("elf") and e.get("elfClass") == "64":
                if any(int(x, 16) < 0x4000 for x in e.get("ptLoad", [])):
                    modern_64_fail.append(f"{zname}/{e['archivePath']}")
            if e["lane"] == "legacy" and e.get("elf") and e.get("elfClass") == "64":
                if any(int(x, 16) < 0x4000 for x in e.get("ptLoad", [])):
                    legacy_debt.append(f"{zname}/{e['archivePath']}")
    if modern_64_fail:
        sys.exit(f"modern 64-bit 16KB gate FAILED: {modern_64_fail}")

    routing_path = os.path.join(a.dist, "routing.json")
    routing = json.load(open(routing_path)) if os.path.isfile(routing_path) else {}

    manifest = {
        "schemaVersion": 2,
        "releaseVersion": a.version,
        "sourceCommit": a.source_commit,
        "builderDigest": lock["builder"]["digest"],
        "termuxPackagesCommit": lock["termuxPackages"]["commit"],
        "metaLineage": lock["metaLineage"],
        "proot": {"tag": lock["dependencies"][0]["tag"], "commit": lock["dependencies"][0]["commit"],
                  "archiveSha256": lock["dependencies"][0]["archiveSha256"]},
        "ndk": lock["toolchain"]["ndk"],
        "ndkVersion": lock["toolchain"].get("ndkVersion"),
        "modernBuildApi": lock["modernSupportBuildApi"],
        "applicationMinSdk": lock["applicationMinSdk"],
        "legacySupportHostRange": lock["legacySupportHostRange"],
        "modernSupportHostRange": lock["modernSupportHostRange"],
        "sourceDateEpoch": lock["sourceDateEpoch"]["value"],
        "archives": archives,
        "modern64Bit16KAligned": len(modern_64_fail) == 0,
        "modern64BitBelow16K": modern_64_fail,
        "legacy64Bit4KDebt": sorted(legacy_debt),
        "routing": routing,
        "perFileInventory": all_entries,
        "wholeApp16KCompatible": False,
        "wholeApp16KNote": "P1F4A produces the support release only. P1F4B must package the "
                           "legacy lane outside nativeLibraryDir and the modern lane inside it; "
                           "the whole APK/AAB is not yet 16 KB compatible.",
    }
    manifest_dir = os.path.join(a.repo_root, "provenance", "releases")
    os.makedirs(manifest_dir, exist_ok=True)
    manifest_path = os.path.join(manifest_dir, f"{a.version}.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    flat_manifest = os.path.join(a.out, f"{a.version}-provenance.json")
    with open(flat_manifest, "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    sbom = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": f"ProotX-Assets-Support-{a.version}",
        "documentNamespace": f"https://github.com/Lord1Egypt/ProotX-Assets-Support/releases/{a.version}",
        "creationInfo": {"created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(lock["sourceDateEpoch"]["value"])),
                         "creators": ["Tool: scripts/release_metadata.py"]},
        "packages": [],
    }
    for c in COMPONENTS:
        sbom["packages"].append({
            "SPDXID": "SPDXRef-Package-" + c["name"].replace("/", "-").replace(".", "-"),
            "name": c["name"], "versionInfo": c["version"],
            "downloadLocation": c["source"], "licenseDeclared": c["license"],
            "licenseConcluded": "NOASSERTION", "copyrightText": "NOASSERTION",
            "comment": c["scope"],
        })
    sbom_path = os.path.join(a.out, f"{a.version}.spdx.json")
    with open(sbom_path, "w") as f:
        json.dump(sbom, f, indent=2, sort_keys=True)
        f.write("\n")

    sums = [(z, archives[z]["sha256"]) for z in ARCHIVES]
    if os.path.isfile(routing_path):
        sums.append(("routing.json", sha256(routing_path)))
    sums.append((os.path.basename(flat_manifest), sha256(flat_manifest)))
    sums.append((os.path.basename(sbom_path), sha256(sbom_path)))
    sums.sort(key=lambda x: x[0])
    with open(os.path.join(a.out, "SHA256SUMS"), "w") as f:
        for name, digest in sums:
            f.write(f"{digest}  {name}\n")

    print(f"manifest: {manifest_path} sha256={sha256(manifest_path)}")
    print(f"sbom:     {sbom_path} sha256={sha256(sbom_path)}")
    print(f"modern 64-bit below 16K: {len(modern_64_fail)}")
    print(f"legacy 64-bit 4KB debt entries: {len(legacy_debt)}")
    for zname in ARCHIVES:
        print(f"{zname}: {archives[zname]['size']} {archives[zname]['sha256']}")


if __name__ == "__main__":
    main()
